CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSID_Winner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemSSIDWinnerSourceSystem] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VX_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ownerid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_DistancetoStadium] [int] NULL,
[lions_dem_PersonicxCluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_BusinessOwner] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_Veteran] [bit] NULL,
[lions_dem_OccupationDetail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_HomePropertyType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_HomeYearBuilt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_HomeOwnerRenter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_HomeLengthofResidence] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_PresenceofChildren] [bit] NULL,
[str_agerange] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_Occupation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_HomeMarketValue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_NewCarBuyer] [bit] NULL,
[lions_dem_KnownOwnedVehicles] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_DominantVehicleLifestyle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_EducationLevel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_flag_CurrentSeasonTicketMember] [bit] NULL,
[lions_flag_FormerSeasonTicketMember] [bit] NULL,
[lions_flag_CurrentGASTM] [bit] NULL,
[lions_flag_FormerGASTM] [bit] NULL,
[lions_flag_CurrentPremiumClubSTM] [bit] NULL,
[lions_flag_FormerPremiumClubSTM] [bit] NULL,
[lions_flag_CurrentLogeBoxSTM] [bit] NULL,
[lions_flag_FormerLogeBoxSTM] [bit] NULL,
[lions_flag_CurrentTunnelClubSTM] [bit] NULL,
[lions_flag_FormerTunnelClubSTM] [bit] NULL,
[lions_flag_CurrentFanPlan] [bit] NULL,
[lions_flag_FormerFanPlan] [bit] NULL,
[lions_flag_CurrentSingleGameBuyer] [bit] NULL,
[lions_flag_FormerSingleGameBuyer] [bit] NULL,
[lions_flag_CurrentGroup] [bit] NULL,
[lions_flag_FormerGroup] [bit] NULL,
[lions_flag_CurrentSecondaryMarketBuyer] [bit] NULL,
[lions_flag_FormerSecondaryMarketBuyer] [bit] NULL,
[lions_flag_CurrentEventBuyer] [bit] NULL,
[lions_flag_FormerEventBuyer] [bit] NULL,
[lions_flag_CurrentLionsFlashRecipient] [bit] NULL,
[lions_flag_FormerLionsFlashRecipient] [bit] NULL,
[lions_flag_CurrentSuiteLeaseHolder] [bit] NULL,
[lions_flag_FormerSuiteLeaseHolder] [bit] NULL,
[lions_flag_CurrentSuiteRental] [bit] NULL,
[lions_flag_FormerSuiteRental] [bit] NULL,
[lions_flag_WiFiUser] [bit] NULL,
[lions_flag_MobileAppDownload] [bit] NULL,
[lions_flag_CurrentOnlineMerchBuyer] [bit] NULL,
[lions_flag_FormerOnlineMerchBuyer] [bit] NULL,
[lions_flag_CurrentCubClubMember] [bit] NULL,
[lions_flag_FormerCubClubMember] [bit] NULL,
[lions_flag_CurrentYouthFootballParticipant] [bit] NULL,
[lions_flag_FormerYouthFootballParticipant] [bit] NULL,
[lions_flag_LionsAlumni] [bit] NULL,
[lions_primaryaccountid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_dem_hhincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_OldAcctNumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_VeritixAccount] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lions_OldArchticsNumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_CONTACT_ID])
GO
